### ISSUE TITLE
Verify headers of Fraud Proofs in Light Clients

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/rollmint#387] opened 2022-05-03 16:05 UTC
There needs to be a way for a Light Client to verify that the state given in a Fraud Proof actually exists on chain and isn't arbitrary state that is created by a malicious node fraud proof.

The desired end state is that when we send a Fraud Proof over ABCI to the Cosmos-SDK we know it's valid.

**Comment by Manav-Aggarwal** [comment] 2022-05-20 05:27
Good place for this: https://github.com/celestiaorg/optimint/blob/main/types/validation.go

**Comment by Manav-Aggarwal** [comment] 2022-11-17 19:25
Duplicate of #440

**Closed by Manav-Aggarwal** 2022-11-17 19:25 UTC
Labels: C: Cevmos
